### ISSUE TITLE
RE2 RT Compatibility

### ISSUE THREAD

**Issue by TheTedder** [TheTedder/REFix#25]
Make the plugin work on current patch RE2. This probably requires minimal work and it may already work out of the box.

**Comment by mustyyyyy** [comment]
Hey man i'm new on github and on modding RE games. I want to disable that annoying mouse accel. I installed your Refix plugin and tried to turn it on with the PluginLoader on ReFramework but it says that the plugin is for another game. Can you please help me?

**Comment by TheTedder** [comment]
> Hey man i'm new on github and on modding RE games. I want to disable that annoying mouse accel. I installed your Refix plugin and tried to turn it on with the PluginLoader on ReFramework but it says that the plugin is for another game. Can you please help me?

I'm working on latest patch compatibility right now. For now, use the Steam betas feature to select the "dx11_non-rt" beta branch of the game.
