### ISSUE TITLE
[Feature request] Option to disable sharpening

### ISSUE THREAD

**Issue by KoKlusz** [TheTedder/REFix#37]
REFramework has a plugin that disables sharpening, but that also breaks TAA. There are hex edits for non-RT builds of RE2 & 3, but not updates (at least I haven't found them). Plus, having this as a mod option would be more convenient and wouldn't require editing the .exe every time you download the game.

**Comment by TheTedder** [comment]
This would be something to look into for reframework itself. It wouldn't make sense for me to add this feature to my mod when it's already mostly implemented in REFramework.
