### ISSUE TITLE
[Feature Request] Just the zombie 30fps fix?

### ISSUE THREAD

**Issue by DaveACG** [TheTedder/REFix#39]
Since the RT update, the known fix for the 30fps (and below) distant zombies no longer works. Since you've managed to fix this longstanding issue with this mod , could it be segregated out (or possibly configured through a config file) to _only_ apply the zombie 30fps fix? This would be especially beneficial for controller players who'd rather avoid the other aspects of this mod.

Thank you.

**Comment by TheTedder** [comment]
Every feature is toggleable in the config file that gets generated the first time you run the mod. You can find it in reframework\data.

**Comment by DaveACG** [comment]
Doh, thanks!
