### ISSUE TITLE
REFix plugin won't load

### ISSUE THREAD

**Issue by StarSpeak** [TheTedder/REFix#41]
For some unknown reason, REFramework refuses to load the REFix.dll plugin file. I am using REFix version 0.5.1-b1 in combination with REFramework version 1.5.2 and the new 1.5.3; none work, and all have the same error message. There is an error with REFramework's plugin_initialize process:

>[REFramework] [error] [PluginLoader] REFix has an exception in reframework_plugin_initialize, skipping...

Other than that, REFramework works fine.

I reinstalled windows, updated it via windows update, disabled any AV/windows defender/etc, installed all system/device drivers, and then re-installed the game, and the error still occurred.

System info:
Win10 Pro x64 build 19045
MSI GeForce 3070 RTX
Intel Core i7 965

The changes REFix brings to the game are awesome, I would love to play RTX RE2 & 3 w/ them implemented.  Please assist.

Attachments:

Log
[re2_framework_log.txt](https://github.com/TheTedder/REFix/files/14304383/re2_framework_log.txt)

Screenshot
![reframework - plugin error](https://github.com/TheTedder/REFix/assets/160161379/eb1c1473-a606-49bd-bb96-45b692cb892a)

**Comment by TheTedder** [comment]
Hi there. Thank you for the detailed error report! I'm sorry that you're having an issue. I do know that I haven't tested the latest version of REFramework with my mod so it may just straight up break. I plan on releasing a new version soon. It's also entirely possible that a recent update to the game broke the mod. Until I get a chance to update it, you can try the following troubleshooting steps. Only move onto the next step if the previous one doesn't work.
1. Ensure that you are using the correct version of the plugin. If you're playing on current patch RE2, download RE2.zip. If you're playing on RE3 current patch, download RE3.zip.
2. Make sure the game is closed and then delete your REFix config file. It can be found at `reframework\data\refix_config.txt`.
3. Uninstall the game and make sure the game folder is deleted. Install the game normally and launch it once. Quit the game, install REFramework 1.5.2 and launch it once. Quit the game again. Then, install REFix. Doing it this way allows the proper folders to generate.

Please let me know if any of these steps solved your problem.

**Comment by StarSpeak** [comment]
Hi Ted, thanks for the quick response.

Before posting here, I tried every combination of REFramework and REFix I could.  I tried sequentially installing each item in the test workflow, launching/quitting between them (as you detailed in step 3).  I tried this on older and brand new installs of Windows, and on steam and windows store versions of RE2 RTX.  I am currently using the newest builds of each.

All scenarios yielded the same results.  Food for thought: could some software/process be blocking the REFix dll from loading? The drive I have the game installed on is exempted from the built-in Windows security apparatus, and I even disabled it while executing the test workflow.

**Comment by TheTedder** [comment]
I was unable to reproduce it with either RE2 or RE3 on my 64bit Windows 10 Pro machine that's on the same build as yours. I think the issue is that your processor is literally from 2008(!) and therefore does not support [AVX2](https://en.wikipedia.org/wiki/Advanced_Vector_Extensions#Advanced_Vector_Extensions_2) instructions, which I happen to have enabled in my build settings. I've attached debug builds for RE2 and RE3 with it turned off but I have to ask how the hell you are able to run these games in the first place xD
[RE2Debug.zip](https://github.com/TheTedder/REFix/files/14394444/RE2Debug.zip)
[RE3Debug.zip](https://github.com/TheTedder/REFix/files/14394445/RE3Debug.zip)

**Comment by StarSpeak** [comment]
Hi Ted, thank you so much for looking into it. Yes the processor is old, but I haven't run into issues before due to it.

You may be onto something.
I tested your debug versions of the plugin with both the steam and microsoft store versions of RE2 RTX, and while I wasn't able to get the plugin to load properly, the error message did change:
```
[2024-02-25 14:37:45.923] [REFramework] [info] [PluginLoader] Loading plugins...
[2024-02-25 14:37:45.925] [REFramework] [error] [PluginLoader] Failed to load \reframework\plugins\REFix.dll
```
![Untitled](https://github.com/TheTedder/REFix/assets/160161379/dd169f69-03cf-4905-939d-14f9c1d86f52)

A little more tinkering and we may have this resolved.

**Comment by TheTedder** [comment]
Darn, I thought that would do it. But hey, that's progress at least! Do you have the latest Visual C++ Redistributable installed? You can grab it here https://aka.ms/vs/17/release/vc_redist.x64.exe.

**Comment by StarSpeak** [comment]
Hi Ted, yes I'm on the most recent version of VC++.  I updated again from your link and restarted before launching the game, just to be sure.  No changes yet.

**Comment by TheTedder** [comment]
Would you be willing to sit down on a discord call and troubleshoot it? My discord username is `tedder` so send me a friend request if you want some 1:1 support.

**Comment by TheTedder** [comment]
Issue closed following 1:1 support session after discovering the user was not playing on an official licensed copy of the game.
